style: Reformatting existing step

diff --git a/.github/workflows/part_docker_push.yaml b/.github/workflows/part_docker_push.yaml
--- a/.github/workflows/part_docker_push.yaml
+++ b/.github/workflows/part_docker_push.yaml
@@ -85,8 +85,13 @@ jobs:
             if [ "$status" == "healthy" ]; then break; fi
             sleep 3
           done
+          # Fail the step if not healthy after 10 retries
+          if [ "$status" != "healthy" ]; then
+            echo "Container did not become healthy after 10 attempts."
+            exit 1
+          fi
           docker stop test_container
-        
+
       # Build and push Docker image with Buildx (don't push on PR)
       # https://github.com/docker/build-push-action
       - name: 🐳🚀 Build and push Docker image
